# Generated by Django 5.2.11 on 2026-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "date",
                    models.CharField(
                        help_text="e.g. 'Feb 12th 2026' or 'Early May 2026'.",
                        max_length=255,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "provisional",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to show a caveat about the date being provisional.",
                    ),
                ),
                (
                    "complete",
                    models.BooleanField(
                        default=False, help_text="Whether the event has passed."
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
