# Generated by Django 4.2.7 on 2023-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_1", models.CharField(max_length=200)),
                ("field_2", models.CharField(max_length=200)),
                ("field_3", models.CharField(max_length=200)),
            ],
        ),
    ]
