# Generated by Django 5.0 on 2023-12-25 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0002_reportrecipient_alter_election_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NominationAdminData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_nomination", models.BooleanField(default=True)),
                (
                    "nomination",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to="nominate.nomination",
                    ),
                ),
            ],
        ),
    ]
