# Generated by Django 5.0 on 2024-01-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0005_alter_rank_membership_delete_votingmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("close_date", models.DateTimeField()),
                (
                    "election",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_info",
                        to="nominate.election",
                    ),
                ),
            ],
        ),
    ]
