# Generated by Django 5.0 on 2024-01-12 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0007_alter_category_options_alter_category_details_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="details",
            new_name="nominating_details",
        ),
    ]
