# Generated by Django 5.0 on 2024-01-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0008_rename_details_category_nominating_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finalist",
            options={"ordering": ["ballot_position"]},
        ),
        migrations.AddField(
            model_name="finalist",
            name="ballot_position",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
