# Generated by Django 5.0 on 2024-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0010_alter_rank_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="voter_ip_address",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
