# Generated by Django 5.0.1 on 2024-01-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0013_alter_category_field_1_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="field_2_required",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="field_3_required",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
