# Generated by Django 5.0.2 on 2024-03-05 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0016_finalist_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nomination",
            options={
                "permissions": [("edit_ballot", "Can edit the ballot as an admin")]
            },
        ),
    ]
