# Generated by Django 5.0.6 on 2024-05-12 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0021_alter_rank_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rank",
            options={
                "permissions": [
                    ("edit_ranking_ballot", "Can edit the ranking ballot as an admin"),
                    (
                        "view_raw_results",
                        "Can view the raw results as the election proceeds",
                    ),
                ]
            },
        ),
    ]
