# Generated by Django 5.0.6 on 2024-05-13 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0023_finalist_short_name"),
        ("nominate", "0024_rank_rank_date"),
    ]

    operations = []
