name: nomnom
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${NOM_DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${NOM_DB_NAME:-nomnom_dev}
      - POSTGRES_USER=${NOM_DB_USER:-nomnom_dev}
      - POSTGRES_PASSWORD=${NOM_DB_PASSWORD:-nomnom-bogon}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready", "-d", "$NOM_DB_NAME", "-u", "$NOM_DB_USER"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    image: redis:7
    ports:
      - "${NOM_REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "_ping"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 5s

  # support
  mailcatcher:
    image: marlonb/mailcrab:latest
    ports:
      - 1080
      - 1025

volumes:
  db-data:
  staticfiles:
