services:
  web:
    image: ghcr.io/worldconvotingsystems/nomnom:dev
    build:
      context: .
    volumes:
      - ".:/app"
    ports:
      - "12333:8000"
    command: /app/docker/start.sh server
    links:
      - db
      - redis
      - mailcatcher
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: true
      NOM_STATIC_FILE_ROOT: /app/staticfiles
      NOM_DB_HOST: db
      NOM_REDIS_HOST: redis
      NOM_EMAIL_HOST: mailcatcher

  worker:
    image: ghcr.io/worldconvotingsystems/nomnom:dev
    command: /app/docker/start.sh worker
    links:
      - db
      - redis
      - mailcatcher
    env_file:
      - .env
    environment:
      NOM_STATIC_FILE_ROOT: /app/staticfiles
      NOM_DB_HOST: db
      NOM_REDIS_HOST: redis
      NOM_EMAIL_HOST: mailcatcher

  flower:
    image: ghcr.io/worldconvotingsystems/nomnom:dev
    command: /app/docker/start.sh flower
    ports:
      - "12344:5555"
    links:
      - db
      - redis
    env_file:
      - .env
    environment:
      NOM_STATIC_FILE_ROOT: /app/staticfiles
      NOM_DB_HOST: db
      NOM_REDIS_HOST: redis

  beat:
    image: ghcr.io/worldconvotingsystems/nomnom:dev
    command: /app/docker/start.sh beat
    links:
      - db
      - redis
    env_file:
      - .env
    environment:
      NOM_STATIC_FILE_ROOT: /app/staticfiles
      NOM_DB_HOST: db
      NOM_REDIS_HOST: redis
