# Generated by Django 5.0.6 on 2024-06-14 15:46

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.manager
import django.utils.timezone
import markdownfield.models
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nominate", "0025_merge_0023_finalist_short_name_0024_rank_rank_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "full_text",
                    markdownfield.models.MarkdownField(
                        rendered_field="rendered_full_text"
                    ),
                ),
                ("rendered_full_text", markdownfield.models.RenderedMarkdownField()),
                (
                    "vote_opens_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("vote_closes_at", models.DateTimeField(null=True)),
                ("can_abstain", models.BooleanField(default=False)),
            ],
            managers=[
                ("is_open", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "selection",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("abstain", "Abstain")],
                        max_length=7,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nominate.nominatingmemberprofile",
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advise.advisoryvote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VoteAdminData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("invalidated", models.BooleanField(default=False)),
                ("comment", models.TextField()),
                (
                    "vote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="advise.vote"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
