# Generated by Django 5.0.6 on 2024-06-14 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryvote",
            name="vote_opens_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
