# Generated by Django 5.0.6 on 2024-06-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0002_alter_advisoryvote_vote_opens_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryvote",
            name="vote_closes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
