# Generated by Django 5.0.6 on 2024-05-16 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hugopacket", "0002_electionpacket_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electionpacket",
            options={
                "permissions": [("preview_packet", "Has early access to the packet")]
            },
        ),
    ]
