# Generated by Django 5.0.6 on 2024-05-16 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nominate", "0025_merge_0023_finalist_short_name_0024_rank_rank_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacketFileGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Allows markdown"),
                ),
                ("position", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ElectionPacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("s3_bucket_name", models.CharField(max_length=255)),
                (
                    "election",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nominate.election",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PacketFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Allows markdown"),
                ),
                ("available", models.BooleanField(default=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("s3_object_key", models.CharField(max_length=65536)),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hugopacket.electionpacket",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hugopacket.packetfilegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
