# Generated by Django 5.0 on 2024-01-12 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nominate", "0007_alter_category_options_alter_category_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("s3_bucket_name", models.CharField(max_length=255)),
                (
                    "election",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nominate.election",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PacketFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("available", models.BooleanField(default=True)),
                ("s3_object_key", models.CharField(max_length=65536)),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hugopacket.packets",
                    ),
                ),
            ],
        ),
    ]
