# Generated by Django 5.2.11 on 2026-03-12 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hugopacket", "0003_alter_electionpacket_options"),
        ("nominate", "0027_alter_category_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packetfile",
            name="group",
        ),
        migrations.AddField(
            model_name="packetfile",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("download", "Download (S3 file)"),
                    ("code", "Distribution Code"),
                ],
                default="download",
                help_text="How members access this content",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="packetfile",
            name="code_display_format",
            field=models.CharField(
                blank=True,
                help_text="Optional format template for CODE type display. Use '#' for each character. Example: '###-#####-###-####' formats 'ABC12345DEF6789' as 'ABC-12345-DEF-6789'. Leave blank for no formatting.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="packetfile",
            name="s3_object_key",
            field=models.CharField(
                help_text="Used for DOWNLOAD type", max_length=65536
            ),
        ),
        migrations.AlterModelOptions(
            name="packetfile",
            options={
                "ordering": ["position"],
                "verbose_name": "Packet Item",
                "verbose_name_plural": "Packet Items",
            },
        ),
        migrations.CreateModel(
            name="DistributionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=500)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this code"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who manually assigned this code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codes_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "packet_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_pool",
                        to="hugopacket.packetfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribution Code",
                "verbose_name_plural": "Distribution Codes",
                "ordering": ["packet_file", "assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="PacketItemAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_accessed_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                (
                    "distribution_code",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_record",
                        to="hugopacket.distributioncode",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packet_accesses",
                        to="nominate.nominatingmemberprofile",
                    ),
                ),
                (
                    "packet_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_accesses",
                        to="hugopacket.packetfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Access",
                "verbose_name_plural": "Item Accesses",
                "ordering": ["-last_accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="PacketSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Supports markdown"),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="hugopacket.electionpacket",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="hugopacket.packetsection",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="packetfile",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: organize files into hierarchical sections",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="hugopacket.packetsection",
            ),
        ),
        migrations.DeleteModel(
            name="PacketFileGroup",
        ),
        migrations.AddConstraint(
            model_name="packetitemaccess",
            constraint=models.UniqueConstraint(
                fields=("packet_file", "member"),
                name="unique_access_per_member_per_file",
            ),
        ),
    ]
