# Generated by Django 5.2.11 on 2026-04-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hugopacket", "0004_remove_packetfile_group_packetfile_access_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packetfile",
            name="s3_object_key",
            field=models.CharField(
                blank=True, help_text="Used for DOWNLOAD type", max_length=65536
            ),
        ),
    ]
