# Generated by Django 5.2.13 on 2026-05-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hugopacket", "0005_alter_packetfile_s3_object_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="packetfile",
            name="size",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="File size in bytes. Automatically set on save.",
                null=True,
            ),
        ),
    ]
