# Generated by Django 5.2.13 on 2026-05-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hugopacket", "0006_packetfile_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="packetfile",
            name="last_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Last modified timestamp for the file. Automatically set on save.",
                null=True,
            ),
        ),
    ]
