# Generated by Django 5.1 on 2025-02-06 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonicalize", "0001_initial"),
        ("nominate", "0026_rankadmindata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryBallot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nominate.category",
                    ),
                ),
                (
                    "nominator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nominate.nominatingmemberprofile",
                    ),
                ),
                (
                    "work_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="canonicalize.work",
                    ),
                ),
                (
                    "work_2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="canonicalize.work",
                    ),
                ),
                (
                    "work_3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="canonicalize.work",
                    ),
                ),
                (
                    "work_4",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="canonicalize.work",
                    ),
                ),
                (
                    "work_5",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="canonicalize.work",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "nominator"),
                        name="unique_nominator_category",
                    )
                ],
            },
        ),
    ]
