# Generated by Django 5.1 on 2025-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonicalize", "0001_initial"),
        ("nominate", "0027_alter_category_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="nominations",
            field=models.ManyToManyField(
                related_name="works",
                through="canonicalize.CanonicalizedNomination",
                to="nominate.nomination",
            ),
        ),
    ]
