# Generated by Django 5.2.9 on 2026-02-07 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonicalize", "0002_alter_work_nominations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="canonicalizednomination",
            options={
                "verbose_name": "Raw Nomination",
                "verbose_name_plural": "Raw Nominations",
            },
        ),
        migrations.AlterModelOptions(
            name="work",
            options={
                "verbose_name": "Canonicalized Work",
                "verbose_name_plural": "Canonicalized Works",
            },
        ),
    ]
