# Generated by Django 5.1 on 2024-11-24 17:29

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0003_remove_proposal_vote_closes_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("preview", "Previewing"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                ],
                default="preview",
                max_length=50,
            ),
        ),
    ]
