# Generated by Django 5.0.1 on 2024-02-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0015_adminmessage_alter_category_field_2_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalist",
            name="name",
            field=models.CharField(default="", max_length=400),
            preserve_default=False,
        ),
    ]
