# Generated by Django 5.0.2 on 2024-03-20 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0017_alter_nomination_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finalist",
            name="name",
        ),
    ]
