# Generated by Django 5.0.2 on 2024-03-20 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0018_remove_finalist_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finalist",
            old_name="description",
            new_name="name",
        ),
    ]
