# Generated by Django 5.0 on 2023-12-29 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0003_nominationadmindata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="nominatingmemberprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convention_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
