# Generated by Django 5.0 on 2024-01-03 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0004_alter_nominatingmemberprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="nominate.nominatingmemberprofile",
            ),
        ),
        migrations.DeleteModel(
            name="VotingMember",
        ),
    ]
