# Generated by Django 5.0 on 2024-01-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0009_alter_finalist_options_finalist_ballot_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="position",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
