# Generated by Django 5.0.1 on 2024-01-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0014_category_field_2_required_category_field_3_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Markdown field for the admin message"),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="field_2_required",
            field=models.BooleanField(
                default=True,
                help_text="This is only relevant if the field count means it'd be included",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="field_3_required",
            field=models.BooleanField(
                default=True,
                help_text="This is only relevant if the field count means it'd be included",
                null=True,
            ),
        ),
    ]
