# Generated by Django 5.0.4 on 2024-04-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0019_rename_description_finalist_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rank",
            constraint=models.UniqueConstraint(
                fields=("membership", "finalist"), name="unique_rank"
            ),
        ),
    ]
