# Generated by Django 5.0.6 on 2024-05-08 04:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0020_rank_unique_rank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rank",
            options={
                "permissions": [
                    ("edit_ballot", "Can edit the ballot as an admin"),
                    (
                        "view_raw_results",
                        "Can view the raw results as the election proceeds",
                    ),
                ]
            },
        ),
    ]
