# Generated by Django 5.1 on 2025-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0026_rankadmindata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="fields",
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
