# Generated by Django 5.2.11 on 2026-04-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominate", "0027_alter_category_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="field_1_used_for_canonicalization",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="field_2_used_for_canonicalization",
            field=models.BooleanField(
                default=True, help_text="Use as part of the canonicalization process"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="field_3_used_for_canonicalization",
            field=models.BooleanField(
                default=True, help_text="Use as part of the canonicalization process"
            ),
        ),
    ]
