---
name: Dependency Check

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1" # Make tools pretty.
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

permissions: {}

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hynek/build-and-inspect-python-package@v2
        id: baipp

    outputs:
      python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}

  dependencies:
    name: Dependency Sanity Check
    runs-on: ubuntu-latest
    needs: build-package

    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: "2025.0.0"

    strategy:
      fail-fast: false
      matrix:
        frozen: ["--frozen", ""]
        python-version: ${{ fromJson(needs.build-package.outputs.python-versions) }}

    steps:
      - uses: actions/setup-python@v5
        id: python-baipp
        with:
          python-version: ${{ matrix.python-version }}

      - uses: extractions/setup-just@v1
      - name: Set up uv
        run: |
          curl -LsSf https://astral.sh/uv/0.4.15/install.sh | sh

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          uv sync ${{ matrix.frozen }} --all-extras --dev

      - name: generate some passwords
        run: |
          DB_PASSWORD=$(openssl rand -hex 8)
          SECRET_KEY=$(openssl rand -hex 16)
          echo "Run-specific DB password: $DB_PASSWORD"
          echo "Run-specific secret key: $SECRET_KEY"
          echo "NOM_DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
          echo "NOM_SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV

      - env:
          NOM_DB_NAME: gha_test
          NOM_DB_HOST: localhost
          NOM_DB_PORT: "52432"
          NOM_DB_USER: gha
          NOM_OAUTH_KEY: bogon
          NOM_OAUTH_SECRET: bogon
          NOM_REDIS_HOST: localhost
          NOM_EMAIL_HOST: localhost
        run: |
          just test
