---
name: Dependency Check

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1" # Make tools pretty.
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

permissions: {}

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hynek/build-and-inspect-python-package@v2
        id: baipp

    outputs:
      python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}

  dependencies:
    name: Dependency Sanity Check
    runs-on: ubuntu-latest
    needs: build-package

    strategy:
      fail-fast: false
      matrix:
        frozen: ["--frozen", ""]
        python-version: ${{ fromJson(needs.build-package.outputs.python-versions) }}

    steps:
      - uses: extractions/setup-just@v1
      - name: Set up uv
        run: |
          curl -LsSf https://astral.sh/uv/0.4.15/install.sh | sh

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          uv sync ${{ matrix.frozen }} --all-extras --dev

      - run: |
          just test
